exclude: |
  (?x)^(
      conda_meta/.+|
      neural_insights/gui.+|
      neural_insights/test.+|
      neural_solution/frontend/.+|
      neural_solution/test/.+|
      neural_coder/extensions/.+|
      examples/.+
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use

  - repo: local
    hooks:
      - id: freeze-requirements
        name: freeze requirements
        entry: bash test.sh
        language: system
        require_serial: true
