
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, test6]
  - repo: https://github.com/psf/black.git
    rev: 25.1.0
    hooks:
      - id: black
        files: (.*\.py)$

