# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Weekly update base images and 3rd party images

on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  freeze-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"

      - name: Set up Git
        run: |
          git config --global user.name "Sun, Xuehao"
          git config --global user.email "xuehao.sun@intel.com"
          git remote set-url origin https://XuehaoSun:"${{ secrets.ACTION_TOKEN }}"@github.com/XuehaoSun/test-azure.git
          git checkout -b update_images_tag

      - name: Run script
        run: |
          echo test >> test.txt

      - name: Commit changes
        run: |
          git add .
          git commit -s -m "Update third party images tag"
          git push --set-upstream origin update_images_tag

      - name: create pull request
        run: gh pr create -B main -H update_images_tag --title 'Update ghcr.io/huggingface/text-generation-inference image tag' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
