# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Weekly update base images and 3rd party images

on:
  workflow_dispatch:

jobs:
  freeze-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Test github actions
        run: |
          latest_vllm_ver=$(curl -s "https://api.github.com/repos/vllm-project/vllm/tags" | jq '.[0].name' -)
          latest_vllm_fork_ver=$(curl -s "https://api.github.com/repos/HabanaAI/vllm-fork/tags" | jq '.[0].name' -)

          echo "latest_vllm_ver=${latest_vllm_ver}" >> "$GITHUB_ENV"
          echo "latest_vllm_fork_ver=${latest_vllm_fork_ver}" >> "$GITHUB_ENV"
      - name: Commit changes
        run: |
          echo "Update vllm version to ${latest_vllm_ver} and ${latest_vllm_fork_ver}"
