name: test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - run: echo "Test"
