name: test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build" && exit 1

  test:
    needs: [build]
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo "Test"
