name: test

on: push

env:
  DOCKER_CONFIG_NAME: "commonDockerConfig"
  REPO_NAME: "intel-extension-for-transformers"
  REPO_TAG: "py38"
  DOCKER_FILE_NAME: "unitTest"
  CONTAINER_NAME: "utTest"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -f codeScan.dockerfile -t ${{ env.REPO_NAME }}:${{ env.REPO_TAG }} .

      - name: Docker Run
        run: |
          docker run -dit --disable-content-trust --privileged --name=${{ env.CONTAINER_NAME }} --shm-size="2g" \
          -v ${{ github.workspace }}:/test ${{ env.REPO_NAME }}:${{ env.REPO_TAG }}

      - name: SparseLib Test
        id: SparseLib-Test
        run: |
          docker exec ${{ env.CONTAINER_NAME }} \
          bash -c "bash /test/test.sh"
        env:
          name: lucky
