name: test

on: push

env:
  DOCKER_CONFIG_NAME: "commonDockerConfig"
  REPO_NAME: "intel-extension-for-transformers"
  REPO_TAG: "py38"
  DOCKER_FILE_NAME: "unitTest"
  CONTAINER_NAME: "utTest"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v3
        with:
          path: world.txt

      - name: Download Reference Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.MY_TOKEN}}
          workflow: model-test.yml
          run_id: ${{ env.REF_ID }}
          path: last_generated
          name_is_regexp: true
          repo: ${{ github.repository }}
          check_artifacts: false
          search_artifacts: false
          skip_unpack: false
          if_no_artifact_found: warn

      - uses: actions/upload-artifact@v3
        with:
          path: last_generated
