name: test

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout out Repo
          uses: actions/checkout@v3
        - name: shell
          run: |
            bash test.sh
          env: 
            name: lucky