name: test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'
      - run: |
          gcloud projects list
          gcloud compute instances list
          gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }}
